### ISSUE TITLE
Crash e fechando o app

### ISSUE THREAD

**Issue by luismelodev** [In-Loco-Media/inlocomedia-android-sdk#1]
Em determinado momento enquanto testava meu app pra colocar em produção:

04-01 11:49:49.591  25409-25409/me.luish.computados W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 25409
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'void in.ubee.private.gw.a(java.lang.String, boolean)' on a null object reference
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at in.ubee.api.ui.views.AdWebView$2.onPageFinished(SourceCode:221)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:507)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at com.android.org.chromium.android_webview.AwWebContentsObserver.didFinishLoad(AwWebContentsObserver.java:40)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at android.os.Looper.loop(Looper.java:145)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5946)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
04-01 11:49:49.596  25409-25409/me.luish.computados W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
04-01 11:49:49.596  25409-25409/me.luish.computados A/chromium﹕ [FATAL:jni_android.cc(269)] Check failed: false. Please include Java exception stack in crash report
04-01 11:49:49.596  25409-25409/me.luish.computados E/chromium﹕ ### WebView Version 40 (1808730-arm) (code 423501)

**Comment by lpmfilho** [comment]
Boa tarde, @luishmelo .
Primeiro, obrigado pelo report.
Detectamos o problema e já estamos corrigindo, ainda esta semana deveremos lançar uma nova versão com a correção.
A fim de compreender melhor o fluxo que causou esse erro, qual tipo de ad você estava utilizando, banner ou interstitial?

**Comment by luismelodev** [comment]
@lpmfilho AdType.DISPLAY_BANNER_SMALL

**Comment by falconegabriel** [comment]
Corrigido no release [1.8.0](https://github.com/In-Loco-Media/inlocomedia-android-sdk/commit/ec02b077fd7f596c40cb4fb4a40a604126483e0a)
