### ISSUE TITLE
Error inserting event_values

### ISSUE THREAD

**Issue by luyzfernando** [In-Loco-Media/inlocomedia-android-sdk#10]
Error is causing application freeze for a few seconds. 

SDK version: 3.5.0

> 04-06 13:19:49.583 7094-7094/br.debug E/InLocoMediaAdI: Timeout
> 04-06 13:19:49.619 7094-7425/br.debug E/SQLiteLog: (1) table events has no column named event_type
> 04-06 13:19:49.629 7094-7420/br.debug I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
> 04-06 13:19:49.632 7094-7425/br.debug E/SQLiteDatabase: Error inserting event_values=[B@379e1ac event_type=ad_load timestamp=1523031589474
>                                                                        android.database.sqlite.SQLiteException: table events has no column named event_type (code 1): , while compiling: INSERT INTO events(event_values,event_type,timestamp) VALUES (?,?,?)
>                                                                        #################################################################
>                                                                        Error Code : 1 (SQLITE_ERROR)
>                                                                        Caused By : SQL(query) error or missing database.
>                                                                        	(table events has no column named event_type (code 1): , while compiling: INSERT INTO events(event_values,event_type,timestamp) VALUES (?,?,?))
>                                                                        #################################################################
>                                                                            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
>                                                                            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1008)
>                                                                            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:573)
>                                                                            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
>                                                                            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
>                                                                            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
>                                                                            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1781)
>                                                                            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1653)
>                                                                            at com.inlocomedia.android.core.private.bj.a(SourceCode:118)
>                                                                            at com.inlocomedia.android.core.private.be.b(SourceCode:334)
>                                                                            at com.inlocomedia.android.core.private.be.a(SourceCode:128)
>                                                                            at com.inlocomedia.android.core.private.bl$2.a(SourceCode:102)
>                                                                            at com.inlocomedia.android.core.private.dy.a(SourceCode:16)
>                                                                            at com.inlocomedia.android.core.private.dy.b(SourceCode:12)
>                                                                            at com.inlocomedia.android.core.private.ds$1.a(SourceCode:49)
>                                                                            at com.inlocomedia.android.core.util.r.run(SourceCode:44)
>                                                                            at com.inlocomedia.android.core.private.eb.a(SourceCode:77)
>                                                                            at com.inlocomedia.android.core.private.ds.a(SourceCode:65)
>                                                                            at com.inlocomedia.android.core.private.dr.a(SourceCode:169)
>                                                                            at com.inlocomedia.android.core.private.dr.p(SourceCode:148)
>                                                                            at com.inlocomedia.android.core.private.dr.n(SourceCode:124)
>                                                                            at com.inlocomedia.android.core.private.dr.b(SourceCode:102)
>                                                                            at com.inlocomedia.android.core.private.dr.a(SourceCode:84)
>                                                                            at com.inlocomedia.android.core.private.dr$a.c(SourceCode:572)
>                                                                            at com.inlocomedia.android.core.private.bl.a(SourceCode:140)
>                                                                            at com.inlocomedia.android.core.private.bl.a(SourceCode:88)
>                                                                            at com.inlocomedia.android.ads.private.aj$4.a(SourceCode:554)
>                                                                            at com.inlocomedia.android.core.private.dy.a(SourceCode:16)
>                                                                            at com.inlocomedia.android.core.private.dy.b(SourceCode:12)
>                                                                            at com.inlocomedia.android.core.private.ds$1.a(SourceCode:49)
>                                                                            at com.inlocomedia.android.core.util.r.run(SourceCode:44)
>                                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
>                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                            at java.lang.Thread.run(Thread.java:762)

**Comment by pedroatanasio** [comment]
@luyzfernando, thank you for letting us know!

We have identified a small problem with our database. The fix is already available in version 3.5.3 of the SDK.

Once again, thank you!

**Comment by luyzfernando** [comment]
Valeu
