### ISSUE TITLE
Can't find in.ubee.api.ads package.

### ISSUE THREAD

**Issue by mauriciogior** [In-Loco-Media/inlocomedia-android-sdk#2]
Where is the source for `in.ubee.api.ads` package?

**Comment by falconegabriel** [comment]
Could you explain a bit more about your issue? 

If you can't find the steps to include our library, check the link bellow:
- https://github.com/In-Loco-Media/inlocomedia-android-sdk/wiki/Getting-Started

**Comment by mauriciogior** [comment]
I followed all steps and included `compile 'com.inlocomedia.android:android-sdk:1.10.+'` in my **gradle** file. The classes inside `in.ubee.api.ads` package are in a **jar** file? I couldn't find them inside the SDK directory.

**Comment by mauriciogior** [comment]
``` gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':api')
    compile project(':view-pager-indicator')
    compile project(':MaterialEditText')
    compile project(':android-easy-db')
    compile project(':CropImage')
    compile project(':ambience')
    compile project(':easyaudiomanager')
    compile 'com.pkmmte.view:circularimageview:1.1'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.android.support:appcompat-v7:21+'
    compile 'com.android.support:cardview-v7:21.+'
    compile 'com.facebook.android:facebook-android-sdk:3.21.1'
    compile 'com.mixpanel.android:mixpanel-android:4.5.3'


    compile 'com.inlocomedia.android:android-sdk:1.10.+'
    compile 'com.google.android.gms:play-services-ads:7.5.0'
    compile 'com.google.android.gms:play-services-location:7.5.0'
}
```

**Comment by falconegabriel** [comment]
Thats the correct way. 

The 'com.inlocomedia.android:android-sdk:1.10.+' contains an Android Archive (AAR) which contains the library. Nothing else needs to be done to import them.
It contains the necessary jars, and you do not need to import it again.
If you have any doubts regarding this, check our sample project [here](https://github.com/In-Loco-Media/inlocomedia-android-sdk/wiki#sample-projects).

Can you tell me which is the problem you are having?
Did you succeed at [Initializing](https://github.com/In-Loco-Media/inlocomedia-android-sdk/wiki/Getting-Started#5-initializing) the SDK? 
Did you try to create an AdView and you could not find the package?

**Comment by mauriciogior** [comment]
When I add the following Activity and Service to my manifest:

``` xml
    <activity
        android:name="in.ubee.api.ads.AdActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
        android:theme="@style/Theme.UBAdActivity" />

    <service android:name="in.ubee.api.location.LocationService" 
        android:exported="false"/>
```

the Android Studio lint can't find the `in.ubee.api` package. This also happens when I try to import anything from `in.ubee.api` package or use in my XML layouts.

Tonight I'll try importing it without gradle to see what happens.

**Comment by falconegabriel** [comment]
Try building the Sample Project to see if it can be done. 
The way you were using seems to be correct. 
I wonder if there is any issue regarding the gradle build or version. 

Can you add me on Skype? My contact is **********. 
If possible, text me when you are working on the project and we will try to solve it faster.

**Comment by mauriciogior** [comment]
I managed to make it work.
The problem was the build tools version. I changed now to `22.0.1` and it's working.

Thank you.
