### ISSUE TITLE
Certificado SSL HTTPS Expirado

### ISSUE THREAD

**Issue by Catbag** [In-Loco-Media/inlocomedia-android-sdk#3]
I/InLocoMedia: Loading AdView. {"user_profile":{},"req_agent":"admob"}

I/InLocoMedia: Ad requested. AdSize: FULLxAUTO_as AdType: smart_banner_-1x-2

W/InLocoMedia: AdRequest has failed with error: gw: SSLHandshakeException: 
com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Fri Nov 13 12:26:01 BRT 2015 (compared to Fri Nov 13 12:59:26 BRT 2015) at url https://ads.ubee.in/api/v3/ad_for?app_id=e438742c4b3f8ee7535176ffd59efbfa4853ebb2e96972aae570f77510a64827

W/InLocoMedia: AdView error: (Internal Error)

I/InLocoMedia: Ad error: Internal Error

**Comment by falconegabriel** [comment]
O problema já foi resolvido, 

Obrigado pelo feedback.
