### ISSUE TITLE
Your app is uploading users' installed apps information

### ISSUE THREAD

**Issue by feliperezende** [In-Loco-Media/inlocomedia-android-sdk#6]
Olá,

Recebi a seguinte mensagem do Google Play após atualizar meu app.

> Your app is uploading users' installed apps information to https://ads.ubee.in/api/v3/user_data without prior proper disclosure.
> Make sure your app is compliant with the User Data policy and all other policies listed in the Developer Program Policies. Remember that additional enforcement could occur if there are further policy issues with your apps.

Existe alguma maneira de desabilitar este upload de apps instaladas?

**Comment by falconegabriel** [comment]
Resolvido
