### ISSUE TITLE
NoClassDefFoundError: android.support.v7.widget.RecyclerView

### ISSUE THREAD

**Issue by raulccabreu** [In-Loco-Media/inlocomedia-android-sdk#7]
Olá, usamos a inlocomedia através da mediação do admob e na última semana este crash começou a aparecer com muita frequência. Só foi corrigido com a adição do `compile 'com.android.support:recyclerview-v7:24.2.0'` às dependências do meu projeto. Suponho que o proguard arrancou a recyclerview do build da lib da inlocomedia. Um `-keep class android.support.v7.widget.** {*;}` no proguard file pode resolver.

**Crash**

```
java.lang.NoClassDefFoundError: android.support.v7.widget.RecyclerView
    at com.inlocomedia.android.private.dp.b(SourceCode:41)
    at com.inlocomedia.android.ads.mraid.a.c(SourceCode:806)
    at com.inlocomedia.android.ads.core.AdContentView.onAttachedToWindow(SourceCode:205)
```

**build.gradle:**

```
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    defaultConfig {
        minSdkVersion 10
        targetSdkVersion 23
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.google.android.gms:play-services-base:9.4.0'
    compile 'com.google.android.gms:play-services-analytics:9.4.0'
    compile 'com.google.android.gms:play-services-ads:9.4.0'
    compile 'com.inlocomedia.android:android-sdk:2.2.6'
    compile 'com.inlocomedia.android:android-admob-adapter:2.2.0'
}
```

**Manifest....**

```
    <application android:allowBackup="true">
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity
            android:name="com.google.android.gms.ads.AdActivity"
android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" />
```

**Inlocomedia init:**

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        InLocoMediaOptions options = InLocoMediaOptions.getInstance(this);
        options.setAdsKey("inlocomedia_app_id");
        options.setLogEnabled(false);
        InLocoMedia.init(this, options);
```

**Comment by larissanpa** [comment]
Olá, Raul

Obrigada por reportar este erro. Ele foi corrigido na nova versão, 2.2.7 (se você utiliza o compile com a versão 2.2.+, o update deverá ser automático). Havia uma verificação relacionada a RecyclerView independentemente da dependência estar presente ou não, que foi corrigida. Você já pode retirar a linha `compile 'com.android.support:recyclerview-v7:24.2.0'` do seu arquivo `build.gradle`. O uso de RecyclerView não é obrigatório, sendo necessário apenas para a utilização de native ads em lista diretamente pelo nosso sdk, o que não é o seu caso.

Mais uma vez, obrigada pelo report.
